Bugfix for vlan_mapping getter
Symptom:
  N3k gets error: undefined method `each' for nil:NilClass

Problem:
  config_get should return the YAML default_value if it doesn't find a match
  but the platform exclude causes it to return nil instead.

  config_get('interface', 'vlan_mapping', @name).each(&:compact!)

  vlan_mapping:
    _exclude: [/N(3|5|6|9)/]
    default_value: []

Minitest didn't catch it because the test was skipped due to a platform check.